config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  
  resources :gigs do
    resources :purchases
    resources :reviews 
  end

  get 'profiles/purchases', to: 'profiles#purchases'
  get 'users/show'
  get 'gigs/search'
  get 'welcome/privacy'
  get 'welcome/terms'
  get 'welcome/help'
  get 'welcome/team'
  get 'welcome/mission'
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#home'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/gig.rb
class Gig < ActiveRecord::Base
	searchkick
	belongs_to :user
  has_many :pictures
  has_many :purchases
  has_many :reviews, :dependent => :destroy
  mount_uploaders :pictures, PicturesUploader
  ratyrate_rateable 'Service'
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	searchkick

	belongs_to :user
	belongs_to :gig

	def paid!
	self.paid = true
	self.save!
		end

    def paid?
	    return true if self.paid
	end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :gig
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :gigs, :dependent => :destroy
  has_many :purchases
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  ratyrate_rater
	searchkick

  def vendor?
    return true if self.vendor == true
  end

end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  # GET /gigs
  # GET /gigs.json
  def index
    if params[:search]
      Gig.reindex
      @gigs = Gig.search(params[:search])
    else
      @gigs = Gig.all
    end
    # Gig.reindex
    # gigs = Gig.search(params[:search])
    # @gigs = Gig.all
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
    @gig = Gig.find(params[:id])
    @review = Review.new
    @reviews = Review.where(gig_id: @gig.id).all
    
  end

  # GET /gigs/new
  def new
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(gig_params)

    respond_to do |format|
      if @gig.save!
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @gig }
      else
        format.html { render :new }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1
  # PATCH/PUT /gigs/1.json
  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # def search
  #   gig.each do |gig|
  #     puts gig.details
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gig
      @gig = Gig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gig_params
      params.require(:gig).permit(:price, :details, :tag, {pictures: []}, :user_id, :title)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def purchases
		@purchase = Purchase.find_by(user_id: current_user.id)
		@purchases = Purchase.where(user_id: current_user.id).all
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

	def index
		@purchase = Purchase.find_by(user_id: current_user.id)
		@purchases = Purchase.where(user_id: current_user.id).all
	end

	def new
	  	@client_token = generate_client_token
	  	@gig = Gig.find(params[:gig_id])
	  	@purchase = Purchase.new(user_id: current_user.id, gig_id: @gig.id)
	end

	def create
		@gig = Gig.find(params[:gig_id])
		@result = Braintree::Transaction.sale(amount: params[:price], payment_method_nonce: params[:payment_method_nonce])
	    if @result.success?
	    	@purchase = Purchase.create(gig_id: @gig.id, user_id: current_user.id, transaction_id: @result.transaction.id)
	    	@purchase.paid!
	    	redirect_to gig_purchase_path(@gig, @purchase), notice: "Transaction processed!"
	    else
	    	flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
	    	gon.client_token = generate_client_token
	    	render :new
	    end
	end

	def show
		@purchase = Purchase.find_by(user_id: current_user.id)
		@purchases = Purchase.where(user_id: current_user.id).all
	end

	private
	def generate_client_token
  		Braintree::ClientToken.generate
	end

	def purchase_params
     	params.require(:purchase).permit(:gig_id, :user_id, :paid, :transaction_id)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index
		@reviews = Review.all
	end

	def new
		@gig = Gig.new
		@review = Review.new(review_params)
	end

	def create
		@review = Review.new(review_params)
		if @review.save
			redirect_to gig_path(review_params[:gig_id])
		else 
			flash[:alert] = "Something went wrong. Please try again!"
		end
	end

	private
	def review_params
        params.require(:review).permit(:content, :gig_id, :user_id)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
	end

  def privacy
  end

  def terms
  end

  def help
  end

  def team
  end

  def mission
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/profiles/_gigs.html.erb
<div class="divider">
  <h2>Featured Services</h2>
</div>
<div class="gigs-container" id="tourpackages-carousel">
  <div class="row">
    <div class="col-xs-18 col-sm-6 col-md-3">
      <div class="thumbnail">
        <img src="http://wjyy.nh1media.com/assets/images/BLOG-LAUNDRY-IMAGE.jpg" alt="">
        <div class="caption">
          <h4>Laundry & Dry-cleaning Services</h4>
          <p>I am a stay at home mom and I offer laundry, dry-cleaning and ironing services. Drop and pickup at anytime in PJ.</p>
          <p><a href="#" class="btn btn-info btn-xs" role="button">View Profile</a> <a href="#" class="btn btn-default btn-xs" role="button">Book Now</a>
          <a class="btn btn-success btn-xs pull-right" role="button">Starting From RM10</a></p>
        </div>
      </div>
    </div>
    <div class="col-xs-18 col-sm-6 col-md-3">
      <div class="thumbnail">
        <img src="http://www.venusbuzz.com/wp-content/uploads/Asian_mother_working_at_home_with_baby_BLD071383.jpg" alt="">
          <div class="caption">
            <h4>Accountancy & Bookeeping Services</h4>
            <p>ACCA-certified accountant with over 10 years of bookeeping experience. Receipts sorting also available.</p>
            <p><a href="#" class="btn btn-info btn-xs" role="button">View Profile</a> <a href="#" class="btn btn-default btn-xs" role="button">Book Now</a>
            <a class="btn btn-success btn-xs pull-right" role="button">Starting From RM50/day</a></p>
        </div>
      </div>
    </div>
    <div class="col-xs-18 col-sm-6 col-md-3">
      <div class="thumbnail">
        <img src="http://previews.123rf.com/images/qifi/qifi1205/qifi120500016/13552362-cooking-grandmother-Stock-Photo-asian-cook-grandmother.jpg" alt="">
          <div class="caption">
            <h4>Healthy Home-cooked Family Meals</h4>
            <p>A choice of healthy family meals cooked with alot of love. Suitable for lunch and dinner.</p>
            <p><a href="#" class="btn btn-info btn-xs" role="button">View Profile</a> <a href="#" class="btn btn-default btn-xs" role="button">Book Now</a>
            <a class="btn btn-success btn-xs pull-right" role="button">Starting From RM10/pax</a></p>
        </div>
      </div>
    </div>
    <div class="col-xs-18 col-sm-6 col-md-3">
      <div class="thumbnail">
        <img src="http://www.spd.org.sg/upload/Updates/2013/12/Updates%20(8.2)%2006122013.jpg" alt="">
          <div class="caption">
            <h4>Professional Web Design Services</h4>
            <p>Highly-skilled web developer with keen eye for detail. Free mockups and design consultation.</p>
            <p><a href="#" class="btn btn-info btn-xs" role="button">View Profile</a> <a href="#" class="btn btn-default btn-xs" role="button">Book Now</a>
            <a class="btn btn-success btn-xs pull-right" role="button">Starting From RM3500</a></p>
        </div>
      </div>
    </div>        
  </div><!-- End row -->      
</div><!-- End container -->

app/views/profiles/_profile.html.erb
<div class="profile-jumbotron">
  <div class="jumbotron-container">
    <img class="img-rounded responsive" width="150" height="150" <%= image_tag @user.avatar %> </>
    <div class="profile-header">
      <h1><%= "#{current_user.name} "%></h1>
    </div>

    <div class="vendor-header">
      <% if current_user.vendor? %>
    	  <h4>Vendor ID: <%= current_user.vendor_identification %></h4>
    	  <h4>Vendor Description: <%= current_user.vendor_description %></h4>
    	  <h4>Vendor Category: <%= current_user.vendor_category %></h4>
    	  <h4>Video: <%= current_user.vendor_video_url %></h4>
	    <% else %>
	      <h4><%= link_to "Show your Talent!!", edit_user_registration_path(current_user) %></h4>
	    <% end %>
    </div>

  </div>
</div>

app/views/profiles/purchases.html.erb
<div class="index">
<div id="wrapper">

<center><h2>My purchases</h2></center><br>

<div id="columns">
    <% @purchases.each do |purchase| %>
    <div class="pin"> 
        <%if !purchase.gig.pictures[0].nil? %>
          <%= image_tag purchase.gig.pictures[0].url(:index) %>
        <% end %>
        <h4><%= purchase.gig.title %></h4>
        <p>MYR<%= purchase.gig.price %></p>
            <%= link_to 'View', gig_path(id: purchase.gig.id), class: "btn btn-info btn-xs" %>
   	</div>
    <% end %>
</div>
</div>
</div>

app/views/purchases/_form.html.erb
<div class="purchase-form">
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
  <h2 class="mbs">Pay service</h2>
  <%= form_tag gig_purchases_path(@gig.id) do%>
    <p>Please enter your payment details:</p>
	<div id="dropin"></div>
    <%= submit_tag "Pay MYR #{@gig.price}", class: "button mt1" %>
    <%= hidden_field_tag "price", @gig.price %>
  	<%end%>
</div>
</div>

<script type="text/javascript">
  function setupBT() {
    braintree.setup("<%= @client_token %>", 'dropin', {
      container: 'dropin'
    });
  }

  if (window.addEventListener)
    window.addEventListener("load", setupBT, false);
  else if (window.attachEvent)
    window.attachEvent("onload", setupBT);
  else window.onload = setupBT;

</script>

app/views/purchases/index.html.erb
<div class="container-blank">
	Your purchases:
	<% @purchases.each do |purchase| %>
	<%= purchase.gig.title %>
	Delivered by: <%= "#{purchase.gig.user.name}" %>
	<%= render 'reviews/form' %>
	<% end %>
</div>

app/views/purchases/new.html.erb
<%= render 'form' %>

app/views/purchases/show.html.erb
<div class="container">
		<h3>Thank you for your purchase.</h3>
		<%= @purchase.gig.title %><br>
		Delivered by <%= link_to "#{@purchase.gig.user.name}", users_show_path(id: @purchase.gig.user.id) %>
</div>

app/views/reviews/_form.html.erb
<%= form_for [@gig, @review], url: gig_reviews_path(@gig.id) do |f| %>

<div class="form-group">
	<label for="comment">Comment:</label>
	<%= f.text_area :content, :class => "form-control" %>
    <%= f.hidden_field :gig_id, value: @gig.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
	<%= submit_tag "Comment", :class => "btn btn-success" %>
</div>
<% end %>

app/views/welcome/help.html.erb
<div class="container">
  <h1>Need Help?</h1>
  <p>Please call our helpdesk at 1-300-8888 or email us at help@toivo.com</p>
</div>

app/views/welcome/home.html.erb
<section>
<%= render 'layouts/jumbotron' %>
<%= render "layouts/content" %>
<%= render "profiles/gigs" %>
</section>

app/views/welcome/mission.html.erb
<div class="container">
  <h1>Our Mission</h1>
  <p>Toivo is a platform that provides opportunities for the physically less abled and the elderly (Talents, as we call them), as well as a chance to help by getting help for everyone else. Talents have a chance to contribute their abilities by offering Services on Toivo. We call them Services, but they can actually be either goods or services offered by our Talents. Please browse through our list of Services and see if there's anything you like. You might be surprised with the quality on offer by the so called 'less-abled'.</p>

  <p>If you see something you like, congratulations! You now have a chance to help by helping out. Trust us, it's different than simply buying something or donating. We believe that you would actually provide opportunites for our Talents to find their purpose. To contribute something to society with their abilities. Just because they're physically less abled, doesn't mean they're not extraordinarily abled in other ways!</p>

  <p>P.s. Toivo means hope in Finnish, because we believe that's what we're offering. Even it only a little bit.</p>
</div>

app/views/welcome/privacy.html.erb
<div class="container">
  <h1>Privacy Policy</h1>
  <p>This privacy policy discloses the privacy practices for Toivo. This privacy policy applies solely to information collected by this web site. It will notify you of the following:</p>
  <ol>
    <li>What personally identifiable information is collected from you through the web site, how it is used and with whom it may be shared.</li>
    <li>What choices are available to you regarding the use of your data.</li>
    <li>The security procedures in place to protect the misuse of your information.</li>
    <li>How you can correct any inaccuracies in the information.</li>
  </ol>
  <strong>Information Collection, Use, and Sharing</strong> 
  <br>
  <p>We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.</p>

  <p>We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order.</p>

  <p>Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.</p>

  <strong>Your Access to and Control Over Information</strong>
  <br>
  <p>You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address or phone number given on our website:<p>
  <ul>
    <li>See what data we have about you, if any.</li>
    <li>Change/correct any data we have about you.</li>
    <li>Have us delete any data we have about you.</li>
    <li>Express any concern you have about our use of your data.</li>
  </ul>
  <strong>Security</strong>
  <br>
  <p>We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.</p>
  <p>Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a closed lock icon at the bottom of your web browser, or looking for "https" at the beginning of the address of the web page.</p>
  <p>While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.</p>
  <strong>Updates</strong>
  <br>
  <p>Our Privacy Policy may change from time to time and all updates will be posted on this page.</p>
</div>

app/views/welcome/team.html.erb
<section id="team">
  <div class="container">
    <div class="divider">
      <h2>Meet The Team</h2>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <ul class="list-inline list-unstyled text-center">
          <li>
             <img class="img-rounded responsive" width="150" height="150" <%= image_tag 'avatars/3.png' %> </>
            <h5>Aaron</h5>
            <p>Chief Voluntary Officer</p>
          </li>
          <li>
             <img class="img-rounded responsive" width="150" height="150" <%= image_tag 'avatars/4.png' %> </>
            <h5>Kevin</h5>
            <p>Chief Happiness Officer</p>
          </li>
          <li>
            <img class="img-rounded" width="150" height="150" <%= image_tag 'avatars/1.png' %> </>
            <h5>Raz</h5>
            <p>Chief Imaginary Officer</p>
          </li>
          <li>
             <img class="img-rounded responsive" width="150" height="150" <%= image_tag 'avatars/2.png' %> </>
            <h5>Sini</h5>
            <p>Chief Kindness Officer</p>
          </li>
      </ul>
    </div>
  </div>
</section>

app/views/welcome/terms.html.erb
<div class="container">
  <h1>Terms of Service</h1>

  <p>Generic Website offers this Web site, including all information, software, products and services available from this Web site or offered as part of or in conjunction with this Web site (the “Web site”), to you, the user, conditioned upon your acceptance of all of the terms, conditions, policies and notices stated here. Generic Website reserves the right to make changes to these Terms and Conditions immediately by posting the changed Terms and Conditions in this location.</p>

  <p>Your continued use of the Web site constitutes your agreement to all such terms, conditions and notices, and any changes to the Terms and Conditions made by Generic Website.</p>

  <p>The term ‘genericwebsite.com’ or ‘us’ or ‘we’ refers to the owner of the website. The term ‘you’ refers to the user or viewer of our website.</p>

  <p>The use of this website is subject to the following terms of use:</p>

  <p>Use the website at your own risk. This website is provided to you “as is,” without warranty of any kind either express or implied. Neither Generic Website nor its employees, agents, third-party information providers, merchants, licensors or the like warrant that the Web site or its operation will be accurate, reliable, uninterrupted or error-free. No agent or representative has the authority to create any warranty regarding the Web site on behalf of Generic Website. Generic Website reserves the right to change or discontinue at any time any aspect or feature of the Web site.</p>

  <strong>Exclusion of Liability</strong>
  <br>
  <p>The content of the pages of this website is for your general information and use only. It is subject to change without notice.</p>

  <p>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</p>

  <strong>Indemnification</strong>
  <br>
  <p>Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.</p>

  <p>This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.</p>

  <p>All trade marks reproduced in this website which are not the property of, or licensed to, the operator are acknowledged on the website.</p>

  <p>Unauthorized use of this website may give rise to a claim for damages and/or be a criminal offense.</p>

  <p>From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).</p>

  <strong>Copyright</strong>
  <br>
  <p>Except for material in the public domain under United States copyright law, all material contained on the Web site (including all software, HTML code, Java applets, Active X controls and other code) is protected by United States and foreign copyright laws. Except as otherwise expressly provided in these terms and conditions, you may not copy, distribute, transmit, display, perform, reproduce, publish, license, modify, rewrite, create derivative works from, transfer, or sell any material contained on the Web site without the prior consent of the copyright owner.</p>

  <p>None of the material contained on Generic Website may be reverse-engineered, disassembled, decompiled, transcribed, stored in a retrieval system, translated into any language or computer language, retransmitted in any form or by any means (electronic, mechanical, photo reproduction, recordation or otherwise), resold or redistributed without the prior written consent of Generic Website. Violation of this provision may result in severe civil and criminal penalties.</p>

</div>