config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  
  resources :gigs do
    resources :purchases
    resources :reviews 
  end

  get 'profiles/purchases', to: 'profiles#purchases'
  get 'users/show'
  get 'gigs/search'
  get 'welcome/privacy'
  get 'welcome/terms'
  get 'welcome/help'
  get 'welcome/team'
  get 'welcome/mission'
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#home'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/gig.rb
class Gig < ActiveRecord::Base
	searchkick
	belongs_to :user
  has_many :pictures
  has_many :purchases
  has_many :reviews, :dependent => :destroy
  mount_uploaders :pictures, PicturesUploader
  ratyrate_rateable 'Service'
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	searchkick

	belongs_to :user
	belongs_to :gig

	def paid!
	self.paid = true
	self.save!
		end

    def paid?
	    return true if self.paid
	end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :gig
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :gigs, :dependent => :destroy
  has_many :purchases
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  ratyrate_rater
	searchkick

  def vendor?
    return true if self.vendor == true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  # GET /gigs
  # GET /gigs.json
  def index
    if params[:search]
      Gig.reindex
      @gigs = Gig.search(params[:search])
    else
      @gigs = Gig.all
    end
    # Gig.reindex
    # gigs = Gig.search(params[:search])
    # @gigs = Gig.all
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
    @gig = Gig.find(params[:id])
    @review = Review.new
    @reviews = Review.where(gig_id: @gig.id).all
    
  end

  # GET /gigs/new
  def new
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(gig_params)

    respond_to do |format|
      if @gig.save!
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @gig }
      else
        format.html { render :new }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1
  # PATCH/PUT /gigs/1.json
  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # def search
  #   gig.each do |gig|
  #     puts gig.details
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gig
      @gig = Gig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gig_params
      params.require(:gig).permit(:price, :details, :tag, {pictures: []}, :user_id, :title)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def purchases
		@purchase = Purchase.find_by(user_id: current_user.id)
		@purchases = Purchase.where(user_id: current_user.id).all
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

	def index
		@purchase = Purchase.find_by(user_id: current_user.id)
		@purchases = Purchase.where(user_id: current_user.id).all
	end

	def new
	  	@client_token = generate_client_token
	  	@gig = Gig.find(params[:gig_id])
	  	@purchase = Purchase.new(user_id: current_user.id, gig_id: @gig.id)
	end

	def create
		@gig = Gig.find(params[:gig_id])
		@result = Braintree::Transaction.sale(amount: params[:price], payment_method_nonce: params[:payment_method_nonce])
	    if @result.success?
	    	@purchase = Purchase.create(gig_id: @gig.id, user_id: current_user.id, transaction_id: @result.transaction.id)
	    	@purchase.paid!
	    	redirect_to gig_purchase_path(@gig, @purchase), notice: "Transaction processed!"
	    else
	    	flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
	    	gon.client_token = generate_client_token
	    	render :new
	    end
	end

	def show
		@purchase = Purchase.find_by(user_id: current_user.id)
		@purchases = Purchase.where(user_id: current_user.id).all
	end

	private
	def generate_client_token
  		Braintree::ClientToken.generate
	end

	def purchase_params
     	params.require(:purchase).permit(:gig_id, :user_id, :paid, :transaction_id)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index
		@reviews = Review.all
	end

	def new
		@gig = Gig.new
		@review = Review.new(review_params)
	end

	def create
		@review = Review.new(review_params)
		if @review.save
			redirect_to gig_path(review_params[:gig_id])
		else 
			flash[:alert] = "Something went wrong. Please try again!"
		end
	end

	private
	def review_params
        params.require(:review).permit(:content, :gig_id, :user_id)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
	end

  def privacy
  end

  def terms
  end

  def help
  end

  def team
  end

  def mission
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gigs/_form.html.erb
<%= form_for(@gig) do |f| %>

  <% if @gig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gig.errors.count, "error") %> prohibited this gig from being saved:</h2>
      <ul>
      <% @gig.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
    <section class="container">
      <div class="container-page">        
   
        <div class="col-md-6">
          
          <div class="form-group col-lg-12">
            <label>Title</label>
            <%= f.text_field :title, class:"form-control" %>
          </div>
          
          <div class="form-group col-lg-12">
            <label>Price</label>
            <%= f.number_field :price, class:"form-control" %>
          </div>
                  
          <div class="form-group col-lg-12">
            <label>Details</label>
            <%= f.text_area :details, class:"form-control" %>
          </div>  

          <div class="form-group col-lg-12">
            <label>Tag</label>
            <%= f.select(:tag, options_for_select([["None", nil], ["Arts & Craft", "Arts & Craft"], ["Literature & Translation", "Literature & Translation"], ["Music & Entertainment", "Music & Entertainment"], ["Tech & IT", "Tech & IT"], ["Education & Training", "Education & Training"], ["Home & Wellbeing", "Home & Wellbeing"]])) %>
          </div>         
          
          <div class="form-group col-lg-12">
            <label>Pictures</label>
            <%= f.file_field :pictures, multiple: true %>
          </div> 

          <%= f.hidden_field :user_id, value: current_user.id %>
          
          <br>
          <div class="form-group col-lg-12"> 
            <button type="submit" class="btn btn-primary">Show Your Talent</button>
          </div>
          
        </div>
      </div>
    </section>
  </div>
<% end %>

app/views/gigs/edit.html.erb
<br>
<br>
<center><h2>Edit Your Talent</h2></center>
<br>
<%= render 'form' %>
<!-- 
<%= link_to 'Show', @gig %> |
<%= link_to 'Back', gigs_path %>
 -->

app/views/gigs/index.html.erb
<body>
<p id="notice"><%= notice %></p>

<div class="index">
<div id="wrapper">

<center><h2>All Services</h2></center><br>

  <%= form_tag(gigs_path, :method => "get", id: "search-form") do %>
    <div class="row">
      <div class="col-md-6">
        <div id="custom-search-input">
          <div class="input-group col-md-12">
          <%= text_field_tag :search, params[:search], placeholder: "Search Services", class:"form-control input-lg" %>
            
            <span class="input-group-btn">
              <%= submit_tag "Search", :name => nil, class:"btn btn-info btn-lg" %>
              
     <!--          <button type="button">
                <i class="glyphicon glyphicon-search"></i>
              </button> -->
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>

    <br>

    <div id="columns">
      <% @gigs.each do |gig| %>
      <div class="pin"> 
          <%if !gig.pictures[0].nil? %>
            <%= image_tag gig.pictures[0].url(:index) %>
          <% end %>
          <h4><%= gig.title %></h4>
          <p>Starting from: MYR<%= gig.price %></p>

              
            <% if gig.user_id == current_user.id %>
              <%= link_to 'View', gig, class: "btn btn-info btn-xs" %>
              <%= link_to 'Edit', edit_gig_path(gig), class: "btn btn-default btn-xs" %>
              <%= link_to 'Delete', gig, class: "btn btn-danger btn-xs pull-right", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
              <%= link_to 'View', gig, class: "btn btn-info btn-xs" %>
              <%= link_to 'Book Now', gig, class: "btn btn-default btn-xs" %>
              <%= link_to 'Purchase', gig, class: "btn btn-success btn-xs pull-right" %>
            <% end %>

        <p>Talent by <%= "#{gig.user.name} "%></p>
        <p><%= gig.tag %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>
</body>

app/views/gigs/new.html.erb
<center><h2>Show Your Talent</h2></center>
<br>
<%= render 'form' %>

app/views/gigs/show.html.erb
<body>
<%= javascript_include_tag 'ratyrate.js', "data-turbolinks-track" => false %>
<div class="container">
    <br>
    <div class="row">
      <div class="col-md-3">
        <% if @gig.user_id != current_user.id %>
          <div class="profile-userbuttons">
           <!--  <button type="button" class="btn btn-success btn-sm"> -->
            <%= link_to "Order Now", new_gig_purchase_path(@gig.id), :class => "btn btn-success btn-sm" %>
          </div>
        <% end %>

        <div class="profile-sidebar">
          <!-- SIDEBAR USERPIC -->
          <div class="profile-userpic">
            <img class="img-responsive" alt="" <%= image_tag @gig.user.avatar %></>
          </div>
          <!-- END SIDEBAR USERPIC -->
          <!-- SIDEBAR USER TITLE -->
          <div class="profile-usertitle">
            <div class="profile-usertitle-name">
              <p>By: <%= link_to "#{@gig.user.name}", users_show_path(id: @gig.user.id) %></p>
            </div>
          </div>
        </div>
        <!-- END SIDEBAR USER TITLE -->
        <!-- SIDEBAR MENU -->
        <div class="profile-usermenu">
          <ul class="nav">
            <li>
              <a href="#">
              <i class="glyphicon glyphicon-flag"></i>
              <%= @gig.tag %></a>
            </li>
            <li>
              <a href="#">
              <i class="glyphicon glyphicon-home"></i>
              <%= @gig.user.email %></a>
            </li>
          </ul>
        </div>
        <!-- END MENU -->
        <!-- SIDEBAR BUTTONS -->
        <% if @gig.user_id == current_user.id %>
          <div class="profile-userbuttons">
            <%= link_to "Edit", edit_gig_path, class: "btn btn-success btn-sm" %><br>
            <%= button_to "Delete", {:controller => "gigs", :action => 'destroy', :id => @gig.id}, :confirm => "Are you sure you want to delete #{@gig.title}?", :method => :delete, class: "btn btn-danger btn-sm" %>
          </div>
        <% end %>
        <!-- END SIDEBAR BUTTONS -->
      </div>

    <div class="col-md-9">
      <div class="profile-content">         
        <% if @gig.pictures %>
      <div class="carousel slide" id="screenshot-carousel" data-rise="carousel"><!-- Variable Carousel -->
       <ol class="carousel-indicators">
         <% @gig.pictures.each_with_index do |picture, index| %>
           <% if index == 0 %>
             <li data-target="screenshot-carousel" data-slide-to="#{index}" class="active"></li>            
           <% else %>
             <li data-target="screenshot-carousel" data-slide-to="#{index}"></li>
           <% end %>
         <% end %>
       </ol>
       <div class="carousel-inner">
         <% @gig.pictures.each_with_index do |picture, index| %>
           <% if index == 0 %>
             <div class="item active">
               <%= image_tag picture.url(:index).to_s %>
             </div>
           <% else %>
             <div class="item">
               <%= image_tag picture.url(:index).to_s %>
             </div>
           <% end %>            
         <% end %>
       </div>
       <a href="#screenshot-carousel" class="left carousel-control" data-slide="prev">
         <span class="glyphicon glyphicon-chevron-left"></span>
       </a>
       <a href="#screenshot-carousel" class="right carousel-control" data-slide="next">
         <span class="glyphicon glyphicon-chevron-right"></span>
       </a>
     </div><!-- End Variable Carousel -->
     <% else %>
     <p>No pictures for this service yet</p>
     <% end %><br>

      <%= rating_for @gig, "Service" %>
      <h2><%= @gig.title %></h2>      
      <p><%= @gig.details %><br></p>
  </div>

  <div class="col-md-12">
    <h3>Comments</h3>
    <% @reviews.each do |review| %>
      <div class="review-content">
      <%= image_tag review.user.avatar, :class => "profile-image img-rounded" %>
      <%= link_to "#{review.user.name}" %><br>
      <%= review.content %>
      </div>
    <% end %>
    <%= render :partial => "reviews/form" %>
  </div>
</div>
</body>

app/views/users/show.html.erb
<div class="profile-jumbotron">
  <div class="jumbotron-container">
    <%= image_tag @user.avatar_url(:profile), class:"img-rounded responsive" %>
    <div class="profile-header">
      <h1><%= @user.name %></h1>
      <h4><%= @user.email %></h4>
      <h4><%= @user.location %></h4>
      <% if @user.vendor? %>
        <h6 style="color:#FF0022"><%= @user.name %> is a Toivo Talent</h6>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <br>
  <% if @user.vendor? %>
    <div class="row">
      <div class="col-lg-7">
        <% if (@user.vendor_video_url == nil || @user.vendor_video_url == "") %>
          <h4>This Talent had not shared any video yet</h4>
        <% else %>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @user.vendor_video_url %>" frameborder="0" allowfullscreen></iframe>
        <% end %>
      </div>
      <div class="col-lg-5">
        <strong>Talent Description:</strong> 
        <p><%= @user.vendor_description %></p>
        <strong>Talent Category:</strong> 
        <p><%= @user.vendor_category %></p>
      </div>
    </div>
  <% else %>
    <% if @user == current_user %>
      <h1><%= link_to "Show your Talent!!", edit_user_registration_path(current_user) %></h1>
    <% end %>
  <% end %>
</div>