config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  
  resources :gigs do
    resources :purchases
    resources :reviews 
  end

  get 'profiles/purchases', to: 'profiles#purchases'
  get 'users/show'
  get 'gigs/search'
  get 'welcome/privacy'
  get 'welcome/terms'
  get 'welcome/help'
  get 'welcome/team'
  get 'welcome/mission'
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#home'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/gig.rb
class Gig < ActiveRecord::Base
	searchkick
	belongs_to :user
  has_many :pictures
  has_many :purchases
  has_many :reviews, :dependent => :destroy
  mount_uploaders :pictures, PicturesUploader
  ratyrate_rateable 'Service'
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	searchkick

	belongs_to :user
	belongs_to :gig

	def paid!
	self.paid = true
	self.save!
		end

    def paid?
	    return true if self.paid
	end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :gig
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :gigs, :dependent => :destroy
  has_many :purchases
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  ratyrate_rater
	searchkick

  def vendor?
    return true if self.vendor == true
  end

end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  # GET /gigs
  # GET /gigs.json
  def index
    if params[:search]
      Gig.reindex
      @gigs = Gig.search(params[:search])
    else
      @gigs = Gig.all
    end
    # Gig.reindex
    # gigs = Gig.search(params[:search])
    # @gigs = Gig.all
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
    @gig = Gig.find(params[:id])
    @review = Review.new
    @reviews = Review.where(gig_id: @gig.id).all
    
  end

  # GET /gigs/new
  def new
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(gig_params)

    respond_to do |format|
      if @gig.save!
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @gig }
      else
        format.html { render :new }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1
  # PATCH/PUT /gigs/1.json
  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # def search
  #   gig.each do |gig|
  #     puts gig.details
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gig
      @gig = Gig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gig_params
      params.require(:gig).permit(:price, :details, :tag, {pictures: []}, :user_id, :title)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index
		@reviews = Review.all
	end

	def new
		@gig = Gig.new
		@review = Review.new(review_params)
	end

	def create
		@review = Review.new(review_params)
		if @review.save
			redirect_to gig_path(review_params[:gig_id])
		else 
			flash[:alert] = "Something went wrong. Please try again!"
		end
	end

	private
	def review_params
        params.require(:review).permit(:content, :gig_id, :user_id)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
	end

  def privacy
  end

  def terms
  end

  def help
  end

  def team
  end

  def mission
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_catbar.html.erb
      <div id="navbar" class="navbar-fixed center-block" data-spy="affix" data-offset-top="197">  
        <div class="con text-center center" >
          <ul class="nav navbar-nav nav-cente center" >
            <li><a href="#">Home & Wellbeing</a></li>
            <li><a href="#">Arts & Craft</a></li>
            <li><a href="#">Tech & IT</a></li>
            <li><a href="#">Education & Training</a></li>
            <li><a href="#">Business & Finance</a></li>
            <li><a href="#">Literature & Translatieon</a></li>
          </ul>
        </div>
      </div>
          <!--
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li><a href="../navbar-static-top/">Static top</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
        </div>-->

app/views/layouts/_content.html.erb
<!-- USP section -->
<div class="container">
  <div class="marketing">
    <div class="row">
      <div class="col-lg-4">
       <img class="img-circle" width="150" height="150" <%= image_tag 'icons/bulb.gif' %> </>
        <h2>Help by Getting Help</h2>
        <p>At Toivo, we believe in helping the less abled by giving them a chance to help us. Because sometimes the physically less abled may be extraordinarily abled in different ways. Give them a chance and find out.</p>
        <p><a class="btn btn-default" href="#howitworks" role="button">Read More &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
 
      <div class="col-lg-4">
        <img class="img-circle" width="150" height="150" <%= image_tag 'icons/check.gif' %> </>
        <h2>Trustworthy Talents</h2>
        <p>Toivo filters our talents through validating identification details. Physically less abled talents may verify their identification through PWD details and elderly talents may do so with NRIC details.</p>
        <p><a class="btn btn-default" href="#howitworks" role="button">Read More &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img class="img-circle" width="150" height="150" <%= image_tag 'icons/image.gif' %> </>
        <h2>Give Something Back</h2>
        <p>Toivo talents have a chance to earn extra income from their abilities and you have a chance to contribute by asking for their help. This forms our core of helping out by asking for help.</p>
        <p><a class="btn btn-default" href="#howitworks" role="button">Read More &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
  </div>
</div>

<!-- FAQs -->
<div class="container" id="howitworks">
  <section>
  <div class="divider">
      <h2>How Toivo Works</h2>
  </div>

    <div class="panel-group" id="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title">
            <a href="#collapse-1" data-toggle="collapse" data-parent="#accordion">
              What is Toivo?
            </a>
          </div><!-- End panel title -->
          <div id="collapse-1" class="panel-collapse collapse">
            <div class="panel-body">
              <p>Toivo is a platform that provides opportunities for the physically less abled and the elderly (Talents, as we call them), as well as a chance to help by getting help for everyone else. Talents have a chance to contribute their abilities by offering Services on Toivo. We call them Services, but they can actually be either goods or services offered by our Talents. Please browse through our list of Services and see if there's anything you like. You might be surprised with the quality on offer by the so called 'less-abled'.</p>

              <p>If you see something you like, congratulations! You now have a chance to help by helping out. Trust us, it's different than simply buying something or donating. We believe that you would actually provide opportunites for our Talents to find their purpose. To contribute something to society with their abilities. Just because they're physically less abled, doesn't mean they're not extraordinarily abled in other ways!</p>

              <p>P.s. Toivo means hope in Finnish, because we believe that's what we're offering. Even it only a little bit.</p>

            </div>
          </div><!-- End Panel collapse -->
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title">
            <a href="#collapse-2" data-toggle="collapse" data-parent="#accordion">
              Who can use Toivo?
            </a>
          </div><!-- End panel title -->
          <div id="collapse-2" class="panel-collapse collapse">
            <div class="panel-body">
              <p>Anyone can use Toivo. You're using it right now! You're free to browse around and be inspired by our Talents. You'll need an account to purchase the awesome Services though. Just click on the sign in link on the top right of the page and share us some basic details and you're set. For now, payments can be made using either a credit card or Paypal accounts.</p>

              <p>To become a Talent though, we'll need more information from you. You'll need to be someone physically less abled or elderly and we need to check that. So we need either details of your PWD identification card or NRIC just to make sure. If you have these with you, awesone! Just click on your profile page and edit your profile. You'll be introduced to a form which lets you identify yourself as a talent and you'll be set. You can now post Services!</p>

            </div>
          </div><!-- End Panel collapse -->
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title">
            <a href="#collapse-3" data-toggle="collapse" data-parent="#accordion">
              How is Toivo different from other disabled job boards?
            </a>
          </div><!-- End panel title -->
          <div id="collapse-3" class="panel-collapse collapse">
            <div class="panel-body">
              <p>Disabled job boards are awesome. They provide opportunities for employment and we need that. But what if a Talent just wants to offer a one time or irregular Service? That's where we come in. We let you get help only when you need to and Talent to offer Services only when they want to.</p>

              <p>Toivo operates as a social enterprise. That means we're a business and need to pay the bills as well. We make income by asking for a fee for every transactions. Right now, this amount is 2.5% of all transactions.</p>
            </div>
          </div><!-- End Panel collapse -->
        </div>
      </div>
    </div><!-- End panel group -->

  </section>
</div><!-- End FAQs -->

<!--divider section-->

<div class="divider">
    <h2>Meet The Team</h2>
</div>

<!--team section-->

<section id="team">
  <div class="team-container">
    <div class="row">
      <div class="col-sm-12">
        <ul class="list-inline list-unstyled text-center">
          <li>
             <img class="img-rounded responsive" width="150" height="150" <%= image_tag 'avatars/3.png' %> </>
            <h5>Aaron</h5>
            <p>Chief Voluntary Officer</p>
          </li>
          <li>
             <img class="img-rounded responsive" width="150" height="150" <%= image_tag 'avatars/4.png' %> </>
            <h5>Kevin</h5>
            <p>Chief Happiness Officer</p>
          </li>
          <li>
            <img class="img-rounded" width="150" height="150" <%= image_tag 'avatars/1.png' %> </>
            <h5>Raz</h5>
            <p>Chief Imaginary Officer</p>
          </li>
          <li>
             <img class="img-rounded responsive" width="150" height="150" <%= image_tag 'avatars/2.png' %> </>
            <h5>Sini</h5>
            <p>Chief Kindness Officer</p>
          </li>
      </ul>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container text-center" style="background-color: #000000">
		<div class="row">
			<div class="col-sm-1"></div>
			<div class="col-sm-2">
			  <div class="pulse_holder">
			    <%= image_tag 'toivo_heart.png', class: "img-responsive pulse_marker", width: 100, height: 100 %>
			    	<div class="pulse_rays"></div>

			  </div>
			</div>
				<div class="col-sm-2">
				<h5>About Toivo</h5>
					<ul class="list-unstyled">
						<li><%= link_to "Our Mission", welcome_mission_path %></li>
						<li><%= link_to "The Team", welcome_team_path %></li>
					</ul>
				</div>
				<div class="col-sm-2">
				<h5>Social</h5>
					<ul class="list-unstyled">
						<li><a href="http://www.facebook.com">Facebook</a></li>
						<li><a href="http://www.twitter.com">Twitter</a></li>
						<li><a href="http://www.blogger.com">Blog</a></li>
					</ul>
				</div>
				<div class="col-sm-2">
				<h5>Support</h5>
					<ul class="list-unstyled">
						<li><%= link_to "Privacy policy", welcome_privacy_path %></li>
						<li><%= link_to "Terms & conditions", welcome_terms_path %></li>
						<li><%= link_to "Helpdesk", welcome_help_path %></li>
					</ul>
				</div>
				<div class="col-sm-2">
				<address>
					<strong>Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by:</strong>
					Aaron, Kevin, Raz, Sini and all our mentors<br>
					2016 Next Academy<br>
				</address>
			</div>
			<div class="col-sm-1"></div>
		</div>
		<p><a href="https://github.com/sinimariak/toivo" style="color:white">Adopt Toivo for your own community <i class="fa fa-github" aria-hidden="true"></i></a></p>
	</div>
</footer>


<script type="text/javascript">

app/views/layouts/_jumbotron.html.erb
<!-- Carousel -->
<div id="myCarousel" class="carousel slide" data-ride="carousel" style="margin-top: -100px; width: 100%;">
  <!-- Indicators -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <div class="videoWrapper">
        <iframe width="1280" height="720" src="https://www.youtube.com/embed/9xPAExHmIxY?start=0&end=23&rel=0&autoplay=1&controls=0&loop=1&showinfo=0" frameborder="0" allowfullscreen=""></iframe>
      </div>
      <div class="carousel-caption">   
          <div class="element">
            <div class="sub-element">Toivo helps special talents find work</div>
            <div class="sub-element">Toivo helps you pay for school</div>
            <div class="sub-element">Toivo gives you hope</div>
          </div>
 
        <p><a id="shakabtn" class="btn btn-lg btn-default" href="#howitworks" role="button">Find out how</a></p>
        <%= form_tag(gigs_path, :method => "get", id: "search-form") do %>
          <div class="row">
            <div class="col-md-6">
              <div id="custom-search-input">
                <div class="input-group col-md-12">
                <%= text_field_tag :search, params[:search], placeholder: "Search Available Services", class:"form-control input-lg" %>
                  
                  <span class="input-group-btn">
                    <%= submit_tag "Search", :name => nil, class:"btn btn-info btn-lg" %>
                  </span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div><!-- /.carousel -->

<style> 
  .videoWrapper {
    position: relative;
    padding-bottom: 56.25%;
    padding-top: 1px;
    height: 0;
  }  
  .videoWrapper iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
</style>

<script type="text/javascript" src="/assets/typed.js"></script>
<script type="text/javascript">

    $(function(){
        $(".element").typed({
            strings: ["First sentence.", "Second sentence."],
            typeSpeed: -1
        });
    });
</script>

app/views/layouts/_jumbotron2.html.erb
<section id="intro-header">
  <div class="container-fluid">
  <!-- row 2 -->
    <div class="row">
      <div class="wrap-headline">
        <h1 class="text-center">Get Help, Give Hope</h1>
        <h2 class="text-center">Hire a professional consultant</h2>
        <hr>
      </div>
      <div class="input-group">
          <input type="text" class="form-control" placeholder="I need someone to help me with...">
          <span class="input-group-btn">
            <button class="btn btn-success" type="button">Search</button>
        </span>
      </div>
    </div>
  </div>
</section>

      

app/views/layouts/_navbar.html.erb
<nav class="navbar main navbar-fixed-top">
  <div class="navbar-inner">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand"><img style="margin-top:-0.6em; height:2em"<%= image_tag 'toivo-small.png'%></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  
      <ul class="nav navbar-nav navbar-right" style="padding-right: 2em; padding-top: 0.65em">
        <% if signed_in? %>

        <li><%= link_to 'View all Services', gigs_path%></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Offer a service<span class="caret"></span></a>
          <ul class="dropdown-menu">
            
            <li><%= link_to 'Register', edit_user_registration_path%></li>
            
            <% if current_user.vendor? %>
              <li><%= link_to 'Provide Services', new_gig_path%></li>
              <li><%= link_to 'Manage Your Services', gigs_path%></li>
            <% end %>
   <!--     <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>  -->
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= "#{current_user.name} "%><img style="margin-top: -0.5em; padding-left: 1em" class="profile-image img-rounded"<%= image_tag current_user.avatar %></></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'View Profile', users_show_path(id: current_user.id) %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path(current_user.id) %></li>
            <li><%= link_to "My purchases", profiles_purchases_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        
        <% else %>

          <li><%= link_to "Log in", new_user_session_path %></li>

        <% end %>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.navbar-inner -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toivo</title>
    <%= include_gon %>

    <link rel="icon" href="http://example.com/favicon.png">
     <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

    <!-- mobile optimization -->
    <meta name=“viewport” content=“width=device width, initial-scale=1.0”>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <!-- Braintree JavaScript -->
    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <%= render partial: "layouts/navbar" %>
    <%= yield %>
    <%=render partial: "layouts/footer" %>
  </body>
</html>